version: '3.7'
services:
  # <mongo DB Setup>
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: test
    ports:
      - 27017:27017
    networks:
      - mongodb
    volumes:
      - mongodb_data_container:/data/db
  # TODO -> CREATE A MONGO-COMPASS SERVICE
networks:
  mongodb:
    driver: bridge

volumes:
  mongodb_data_container:
